In [2]:
import scipy
import numpy as np

In [41]:
def code_CSR(matrix):
    data = list()
    indices = list()
    indptr = np.zeros(matrix.shape[0] + 1).astype(int)
    nb_non_null = 0
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if matrix[i, j] != 0:
                data.append(matrix[i, j])
                indices.append(j)
                nb_non_null += 1
        indptr[i + 1] = nb_non_null
    
    return data, indices, indptr

In [78]:
def sparce_matrix_vector_multiplication(sparse_matrix_CSR, vector):
    NNdata, NNindices, indptr = sparse_matrix_CSR
    res = np.zeros(len(indptr) - 1)
    for i in range(len(indptr) - 1):
        res[i] = sum(vector[NNindices[k]] * NNdata[k] for k in range(indptr[i], indptr[i + 1]))
    return res

In [69]:
matrix = np.matrix("0 0 1 0 2;0 2 3 0 0;0 0 0 0 4;0 0 1 0 0")
vector = np.array([1, 2, 3, 0, 2])

In [70]:
sparce_matrix_vector_multiplication(code_CSR(matrix), vector)

([1, 2, 2, 3, 4, 1], [2, 4, 1, 2, 4, 2], array([0, 2, 4, 5, 6]))
[2, 4]
[1, 2]
[1, 2]
[2, 3]
[4]
[4]
[2]
[1]


array([  7.,  13.,   8.,   3.])

In [52]:
scipy.dot(matrix, vector)

matrix([[ 7, 13,  8,  3]])

In [92]:
%%time
scipy.dot(matrix, vector)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 52 µs


matrix([[ 7, 13,  8,  3]])

In [73]:
matrix_CSR = code_CSR(matrix)

In [85]:
%%time
sparce_matrix_vector_multiplication(matrix_CSR, vector)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 67 µs


array([  7.,  13.,   8.,   3.])

In [94]:
import scipy.sparse

In [95]:
sparse_matrix = scipy.sparse.csr_matrix(matrix)

In [ ]:
%%time
scipy.dot()